"""revisado monitored

Revision ID: 09eddcea1fc5
Revises: 8bcaa072db03
Create Date: 2025-07-29 13:51:05.599689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09eddcea1fc5'
down_revision: Union[str, Sequence[str], None] = '8bcaa072db03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'monitored',
               existing_type=postgresql.ENUM('YES_MANUAL', 'YES_AUTOMATED', 'NO', 'yes automated', 'yes manual', 'No', name='monitoredenum'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'monitored',
               existing_type=sa.String(),
               type_=postgresql.ENUM('YES_MANUAL', 'YES_AUTOMATED', 'NO', 'yes automated', 'yes manual', 'No', name='monitoredenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
