"""revisado modelo RansomwareEntry2

Revision ID: 0ad3890077b4
Revises: b2cc98ec48e3
Create Date: 2025-07-29 12:56:41.116435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad3890077b4'
down_revision: Union[str, Sequence[str], None] = 'b2cc98ec48e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
