"""add_ai_summary_and_tags_to_ransomware_entries

Revision ID: 7c90b35fb28c
Revises: 09eddcea1fc5
Create Date: 2025-07-30 12:03:24.508078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c90b35fb28c'
down_revision: Union[str, Sequence[str], None] = '09eddcea1fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ransomware_entries', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('ransomware_entries', sa.Column('ai_tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ransomware_entries', 'ai_tags')
    op.drop_column('ransomware_entries', 'ai_summary')
    # ### end Alembic commands ###
