"""add screenshotUrl to forum_posts

Revision ID: 88c56836ced1
Revises: ce7c5cc40e02
Create Date: 2025-07-22 09:12:10.771050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c56836ced1'
down_revision: Union[str, Sequence[str], None] = 'ce7c5cc40e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_posts', sa.Column('screenshotUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_posts', 'screenshotUrl')
    # ### end Alembic commands ###
