"""revisado modelo RansomwareEntry4

Revision ID: 994749e8a3de
Revises: 4376981d73d6
Create Date: 2025-07-29 13:30:06.530666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '994749e8a3de'
down_revision: Union[str, Sequence[str], None] = '4376981d73d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'monitored',
               existing_type=postgresql.ENUM('YES_MANUAL', 'YES_AUTOMATED', 'NO', 'yes automated', 'yes manual', 'No', name='monitoredenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'monitored',
               existing_type=postgresql.ENUM('YES_MANUAL', 'YES_AUTOMATED', 'NO', 'yes automated', 'yes manual', 'No', name='monitoredenum'),
               nullable=False)
    # ### end Alembic commands ###
