"""changed Ransomware model to RansomwareGroup and RansomwareEntry

Revision ID: a5b6d3ca549c
Revises: 88c56836ced1
Create Date: 2025-07-29 11:26:23.488479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b6d3ca549c'
down_revision: Union[str, Sequence[str], None] = '88c56836ced1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
