"""revisado modelo RansomwareEntry2

Revision ID: b2cc98ec48e3
Revises: c3b1ed74dfd2
Create Date: 2025-07-29 12:53:44.023541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2cc98ec48e3'
down_revision: Union[str, Sequence[str], None] = 'c3b1ed74dfd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
