"""revisado modelo RansomwareEntry

Revision ID: c3b1ed74dfd2
Revises: a5b6d3ca549c
Create Date: 2025-07-29 12:29:13.571014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3b1ed74dfd2'
down_revision: Union[str, Sequence[str], None] = 'a5b6d3ca549c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ransomware')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ransomware',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('BreachName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Rank', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('DetectionDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('Country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('OriginalSource', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Group', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('Download', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sources.id'], name=op.f('ransomware_sources_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ransomware_sources_pkey'))
    )
    # ### end Alembic commands ###
