"""añadir campos ai_summary y ai:tags a ForumPost

Revision ID: ce7c5cc40e02
Revises: d80c76b6dd8e
Create Date: 2025-07-21 12:13:54.725225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7c5cc40e02'
down_revision: Union[str, Sequence[str], None] = 'd80c76b6dd8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_posts', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('forum_posts', sa.Column('ai_tags', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_posts', 'ai_tags')
    op.drop_column('forum_posts', 'ai_summary')
    # ### end Alembic commands ###
