"""modificada tabla ransomware

Revision ID: d5d0fcefde6e
Revises: 
Create Date: 2025-07-04 13:34:24.443081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5d0fcefde6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ransomware_sources')
    op.drop_table('telegram_channels')
    op.add_column('ransomware', sa.Column('BreachName', sa.String(), nullable=False))
    op.add_column('ransomware', sa.Column('Domain', sa.String(), nullable=True))
    op.add_column('ransomware', sa.Column('Rank', sa.String(), nullable=True))
    op.add_column('ransomware', sa.Column('Category', sa.String(), nullable=True))
    op.add_column('ransomware', sa.Column('DetectionDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('ransomware', sa.Column('Country', sa.String(), nullable=False))
    op.add_column('ransomware', sa.Column('OriginalSource', sa.String(), nullable=True))
    op.add_column('ransomware', sa.Column('Group', sa.String(), nullable=False))
    op.add_column('ransomware', sa.Column('Download', sa.String(), nullable=True))
    op.drop_column('ransomware', 'leak_site')
    op.drop_column('ransomware', 'victim_count')
    op.drop_column('ransomware', 'group_name')
    op.drop_column('ransomware', 'last_leak')
    op.alter_column(
        'sources',
        'monitored',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('YES_MANUAL', 'YES_AUTOMATED', 'NO', name='monitoredenum'),
        existing_nullable=False,
        postgresql_using="monitored::monitoredenum"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'sources',
        'monitored',
        existing_type=sa.Enum('YES_MANUAL', 'YES_AUTOMATED', 'NO', name='monitoredenum'),
        type_=sa.VARCHAR(),
        existing_nullable=False
    )
    op.add_column('ransomware', sa.Column('last_leak', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ransomware', sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ransomware', sa.Column('victim_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('ransomware', sa.Column('leak_site', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ransomware', 'Download')
    op.drop_column('ransomware', 'Group')
    op.drop_column('ransomware', 'OriginalSource')
    op.drop_column('ransomware', 'Country')
    op.drop_column('ransomware', 'DetectionDate')
    op.drop_column('ransomware', 'Category')
    op.drop_column('ransomware', 'Rank')
    op.drop_column('ransomware', 'Domain')
    op.drop_column('ransomware', 'BreachName')
    op.create_table('telegram_channels',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('member_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_message_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sources.id'], name=op.f('telegram_sources_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('telegram_sources_pkey'))
    )
    op.create_table('ransomware_sources',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('leak_site', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('victim_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_leak', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['sources.id'], name=op.f('ransomware_sources_id_fkey1')),
    sa.PrimaryKeyConstraint('id', name=op.f('ransomware_sources_pkey1'))
    )
    # ### end Alembic commands ###
