"""modificada tabla ransomware country can be null

Revision ID: ee8985c9562c
Revises: d5d0fcefde6e
Create Date: 2025-07-04 14:27:36.337845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8985c9562c'
down_revision: Union[str, Sequence[str], None] = 'd5d0fcefde6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ransomware', 'Country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ransomware', 'Country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
